/*
 * gpio.h
 *
 *  Created on: 27.12.2016
 *  Based on work of: freddiechopin.info
 *      Author: korgeaux
 */

#ifndef MISC_GPIO_H_
#define MISC_GPIO_H_

#define GPIO_MODER_mask                     3
#define GPIO_MODER_IN_value                 0
#define GPIO_MODER_OUT_value                1
#define GPIO_MODER_ALT_value                2
#define GPIO_MODER_ANALOG_value             3

#define GPIO_OTYPER_mask                    1
#define GPIO_OTYPER_PP_value                0
#define GPIO_OTYPER_OD_value                1

#define GPIO_OSPEEDR_mask                   3
#define GPIO_OSPEEDR_LOW_value              0
#define GPIO_OSPEEDR_MED_value              1
#define GPIO_OSPEEDR_HIGH_value             3

#define GPIO_PUPDR_mask                     3
#define GPIO_PUPDR_FLOATING_value           0
#define GPIO_PUPDR_PULL_UP_value            1
#define GPIO_PUPDR_PULL_DOWN_value          2

#define GPIO_AFRx_mask                      7
#define GPIO_AFRx_AF0_value                 0
#define GPIO_AFRx_AF1_value                 1
#define GPIO_AFRx_AF2_value                 2
#define GPIO_AFRx_AF3_value                 3
#define GPIO_AFRx_AF4_value                 4
#define GPIO_AFRx_AF5_value                 5
#define GPIO_AFRx_AF6_value                 6
#define GPIO_AFRx_AF7_value                 7

#define GPIO_GET_MODER(combination)         (((combination) & 0xF) >> 0)
#define GPIO_GET_OTYPER(combination)        (((combination) & 0xF0) >> 4)
#define GPIO_GET_OSPEEDR(combination)       (((combination) & 0xF00) >> 8)
#define GPIO_GET_PUPDR(combination)         (((combination) & 0xF000) >> 12)
#define GPIO_GET_AFR(combination)           (((combination) & 0xF0000) >> 16)

#define GPIO_COMBINE(moder, otyper, ospeedr, pupdr, afr)    ((moder) | ((otyper) << 4) | ((ospeedr) << 8) | ((pupdr) << 12) | ((afr) << 16))

#define GPIO_IN_FLOATING                    GPIO_COMBINE(GPIO_MODER_IN_value, 0, 0, GPIO_PUPDR_FLOATING_value, 0)
#define GPIO_IN_PULL_UP                     GPIO_COMBINE(GPIO_MODER_IN_value, 0, 0, GPIO_PUPDR_PULL_UP_value, 0)
#define GPIO_IN_PULL_DOWN                   GPIO_COMBINE(GPIO_MODER_IN_value, 0, 0, GPIO_PUPDR_PULL_DOWN_value, 0)

#define GPIO_OUT_PP_LOW                     GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, 0)
#define GPIO_OUT_PP_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, 0)
#define GPIO_OUT_PP_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, 0)
#define GPIO_OUT_PP_MED                     GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, 0)
#define GPIO_OUT_PP_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, 0)
#define GPIO_OUT_PP_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, 0)
#define GPIO_OUT_PP_HIGH                    GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, 0)
#define GPIO_OUT_PP_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, 0)
#define GPIO_OUT_PP_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, 0)
#define GPIO_OUT_OD_LOW                     GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, 0)
#define GPIO_OUT_OD_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, 0)
#define GPIO_OUT_OD_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, 0)
#define GPIO_OUT_OD_MED                     GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, 0)
#define GPIO_OUT_OD_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, 0)
#define GPIO_OUT_OD_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, 0)
#define GPIO_OUT_OD_HIGH                    GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, 0)
#define GPIO_OUT_OD_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, 0)
#define GPIO_OUT_OD_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_OUT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, 0)

#define GPIO_AF0_PP_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_PP_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_PP_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_PP_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_PP_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_PP_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_PP_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_PP_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_PP_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_OD_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_OD_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_OD_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_OD_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_OD_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_OD_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_OD_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_OD_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF0_value)
#define GPIO_AF0_OD_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF0_value)

#define GPIO_AF1_PP_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_PP_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_PP_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_PP_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_PP_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_PP_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_PP_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_PP_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_PP_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_OD_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_OD_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_OD_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_OD_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_OD_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_OD_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_OD_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_OD_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF1_value)
#define GPIO_AF1_OD_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF1_value)

#define GPIO_AF2_PP_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_PP_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_PP_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_PP_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_PP_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_PP_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_PP_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_PP_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_PP_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_OD_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_OD_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_OD_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_OD_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_OD_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_OD_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_OD_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_OD_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF2_value)
#define GPIO_AF2_OD_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF2_value)

#define GPIO_AF3_PP_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_PP_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_PP_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_PP_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_PP_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_PP_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_PP_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_PP_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_PP_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_OD_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_OD_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_OD_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_OD_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_OD_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_OD_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_OD_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_OD_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF3_value)
#define GPIO_AF3_OD_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF3_value)

#define GPIO_AF4_PP_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_PP_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_PP_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_PP_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_PP_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_PP_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_PP_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_PP_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_PP_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_OD_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_OD_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_OD_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_OD_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_OD_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_OD_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_OD_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_OD_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF4_value)
#define GPIO_AF4_OD_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF4_value)

#define GPIO_AF5_PP_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_PP_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_PP_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_PP_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_PP_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_PP_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_PP_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_PP_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_PP_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_OD_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_OD_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_OD_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_OD_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_OD_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_OD_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_OD_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_OD_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF5_value)
#define GPIO_AF5_OD_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF5_value)

#define GPIO_AF6_PP_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_PP_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_PP_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_PP_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_PP_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_PP_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_PP_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_PP_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_PP_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_OD_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_OD_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_OD_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_OD_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_OD_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_OD_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_OD_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_OD_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF6_value)
#define GPIO_AF6_OD_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF6_value)

#define GPIO_AF7_PP_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_PP_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_PP_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_PP_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_PP_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_PP_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_PP_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_PP_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_PP_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_PP_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_OD_LOW                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_OD_LOW_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_OD_LOW_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_LOW_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_OD_MED                     GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_OD_MED_PULL_UP             GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_OD_MED_PULL_DOWN           GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_MED_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_OD_HIGH                    GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_FLOATING_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_OD_HIGH_PULL_UP            GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_UP_value, GPIO_AFRx_AF7_value)
#define GPIO_AF7_OD_HIGH_PULL_DOWN          GPIO_COMBINE(GPIO_MODER_ALT_value, GPIO_OTYPER_OD_value, GPIO_OSPEEDR_HIGH_value, GPIO_PUPDR_PULL_DOWN_value, GPIO_AFRx_AF7_value)

#define GPIO_ANALOG                         GPIO_COMBINE(GPIO_MODER_ANALOG_value, 0, 0, GPIO_PUPDR_FLOATING_value, 0)

void GpioInit(void);
void GpioConfig(GPIO_TypeDef *gpio, uint32_t pin, uint32_t configuration);

#endif /* MISC_GPIO_H_ */
